# -*- coding: utf-8 -*-
"""Penentu Kelayakan Ekstra

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZIBCYd9zyU_K0iMQxtAOJOB0c1l5htNa
"""

def hitung_kelayakan_sertifikat():

    TOTAL_PERTEMUAN = 12
    print("======================================================")
    print(" Program Penilaian Keaktifan & Kelayakan Sertifikasi ")
    print("======================================================")

    print("\n--- Bagian 1: Input Data Diri ---")
    nama = input("Masukkan nama Anda: ")
    nama_kapital = nama.upper()
    print(f"Nama Anda: {nama_kapital}")

    print("\n--- Bagian 2: Input Kehadiran ---")

    while True:
        try:
            masuk = int(input("Jumlah MASUK : "))
            tidak_masuk_tugas = int(input("Jumlah TIDAK MASUK (tapi mengerjakan tugas): "))
            tidak_masuk = int(input("Jumlah TIDAK MASUK (tanpa keterangan/alpha): "))
            total_input_pertemuan = masuk + tidak_masuk_tugas + tidak_masuk

            if total_input_pertemuan != TOTAL_PERTEMUAN:
                print(f"\n[ERROR] Total pertemuan yang Anda masukkan ({total_input_pertemuan}) tidak sesuai.")
                print(f"Total pertemuan seharusnya {TOTAL_PERTEMUAN}. Silakan ulangi.\n")
            elif masuk < 0 or tidak_masuk_tugas < 0 or tidak_masuk < 0:
                 print("\n[ERROR] Jumlah pertemuan tidak boleh negatif. Silakan ulangi.\n")
            else:
                 print("Input Kehadiran valid.")
                 break

        except ValueError:
            print("\n[ERROR] Input harus berupa angka bulat. Silakan ulangi.\n")

    poin_kehadiran = (masuk * 1) + (tidak_masuk_tugas * 0.5) + (tidak_masuk * 0)
    presentase_kehadiran = (poin_kehadiran / TOTAL_PERTEMUAN) * 100

    print("\n--- Bagian 3: Input Nilai Ujian ---")

    while True:
      try:
        ujian_tulis = int(input("Nilai Ujian Tulis (0-100): "))
        ujian_lisan = int(input("Nilai Ujian Lisan (0-100): "))
        ujian_praktek = int(input("Nilai Ujian Praktek (0-100): "))
        total_input_ujian = ujian_tulis + ujian_lisan + ujian_praktek

        if not (0 <= ujian_tulis <= 100 and 0 <= ujian_lisan <= 100 and 0 <= ujian_praktek <= 100):
          print("\n[ERROR] Jumlah nilai ujian tidak boleh kurang dari 0 dan lebih dari 100. Silakan ulangi.\n")
        else:
          print("Input Nilai Ujian valid.")
          break

      except ValueError:
        print("\n[ERROR] Input harus berupa angka. Silakan ulangi.\n")

    nilai_ujian = (ujian_tulis * 0.3) + (ujian_lisan * 0.3) + (ujian_praktek * 0.4)
    predikat_keaktifan = (presentase_kehadiran * 0.5) + (nilai_ujian * 0.5)

    if predikat_keaktifan >= 90:
      category = "SANGAT AKTIF"
    elif 75 <= predikat_keaktifan < 90:
      category = "AKTIF"
    elif 60 <= predikat_keaktifan < 75:
      category = "CUKUP AKTIF"
    elif 25 <= predikat_keaktifan < 60:
      category = "KURANG AKTIF"
    else:
      category = "TIDAK AKTIF"

    print("\n===============================================")
    print("             HASIL PENILAIAN KESEJAHTERAAN          ")
    print("=================================================")

    print(f"\nPresentase Kehadiran: {presentase_kehadiran:.2f}%")
    print(f"Nilai Ujian: {nilai_ujian:.2f}")

    syarat_kehadiran_terpenuhi = presentase_kehadiran >= 75
    syarat_ujian_terpenuhi = nilai_ujian >= 75

    print("\n=========== STATUS KELAYAKAN SERTIFIKASI ===========")
    if syarat_kehadiran_terpenuhi and syarat_ujian_terpenuhi:
      print("\nSELAMAT! Anda dinyatakan LAYAK mendapatkan sertifikat")
    else:
      print("\nMOHON MAAF. Anda dinyatakan TIDAK LAYAK mendapatkan sertifikat")
      if not syarat_kehadiran_terpenuhi:
        print(f" -Alasan : Presentase kehadiran {presentase_kehadiran:.2f}% kurang dari minimum 75%")
      if not syarat_ujian_terpenuhi:
        print(f" -Alasan : Nilai ujian {nilai_ujian:.2f} kurang dari minimum 75")

    keterangan_keaktifan_rapor = predikat_keaktifan

    print("\n=========== KETERANGAN KEAKTIFAN SISWA ===========")
    print(f"\nKeterangan Keaktifan: {keterangan_keaktifan_rapor:.2f}")
    print(f"Ananda {nama_kapital} dinyatakan {category} dalam pertemuan Ekstrakulikuler EC ")

if __name__ == "__main__":
  hitung_kelayakan_sertifikat()